resolver: lts-13.22

packages:
- .
# - prelude
# - lorentz-contracts
# - indigo


extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- first-class-families-0.6.0.0@sha256:9d2a2a0092dfb8fd0e688b0b6bf71242fbc393c028b0b669d25ed387667490c2
- morley-0.5.0
- morley-prelude-0.3.0@sha256:9e9473ac14cfa206adf0a3700764c0251de05042f1fe45daf9cb8556079ae663

  # morley-0.5.0 doesn't come with a version of morley-ledgers on hackage
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    4d825ab1ca9adcafa368a057b18bacfb220ae939 # 0.5.0
  subdirs:
    # - .
    # - prelude
    # - morley-upgradeable
    - morley-ledgers
    - morley-ledgers-test
    # - indigo

- git:
    https://github.com/tqtezos/lorentz-contract-param.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    f6434e40c10ede0261e9f76d1ef039d23f257a34 # 2.0.5.0.0
  subdirs:
    - .

- tasty-hunit-compat-0.2@sha256:71e077ae5c514fadd4586efc19315f10fa5f3c94770820f68f63768441d665f7,1199

nix:
  shell-file: shell.nix
